### ISSUE TITLE
event issue

### ISSUE THREAD

**Issue by realCallMeJ** [ND-Framework/ND_Police#14]
when changing characters, console says:
![image](https://github.com/ND-Framework/ND_Police/assets/73816044/de44e568-74de-4726-8b04-8753509cc65a)
this appears to be the root of the issue:
`bridge/nd/client.lua:28`
```lua
AddEventHandler("ND:characterUnloaded", function()
    TriggerEvent("ND_Police:playerUnloaded")
end)
```

**Comment by Andyyy7666** [comment]
Using `RegisterNetEvent` instead of `AddEventHandler` should fix this.

**Comment by realCallMeJ** [comment]
got it, just wasn't sure if that was safe to do or not
will PR
